### ISSUE TITLE
初始化视频地址失败，请检查课程是否以加入课程表，或官网是否更新API.

### ISSUE THREAD

**Issue by addstone** [lxy2018/TencentCourse-Downloader#1]
Traceback (most recent call last):
  File "c:\workspace\github\TencentCourse-Downloader\main.py", line 323, in <module>
    Login().main()
  File "c:\workspace\github\TencentCourse-Downloader\login.py", line 49, in main
    self.login()
  File "c:\workspace\github\TencentCourse-Downloader\login.py", line 26, in login
    page.goto(self.load_initial_url())
  File "c:\workspace\github\TencentCourse-Downloader\login.py", line 143, in load_initial_url
    raise Exception("初始化视频地址失败，请检查课程是否以加入课程表，或官网是否更新API.")
Exception: 初始化视频地址失败，请检查课程是否以加入课程表，或官网是否更新API.

**Comment by lxy2018** [comment]
看了下没更新api，不过课程详情的api更新了需要带referer。你可以再试一下，或者看下你的课程视频能否加入了课程表，以及能够正常在网页观看。
